### ISSUE TITLE
Version 0.0.27 cannot be installed on etherpad 1.8.7

### ISSUE THREAD

**Issue by ypapouin** [ether/ep_copy_paste_images#30]
```
[2021-01-27 08:10:14.792] [WARN] console - TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.resolve (path.js:1080:7)
    at loadPlugin (/opt/etherpad-lite/src/static/js/pluginfw/plugins.js:114:28)
    at Promise.all.Object.keys.map (/opt/etherpad-lite/src/static/js/pluginfw/plugins.js:77:35)
    at Array.map (<anonymous>)
    at Object.exports.update (/opt/etherpad-lite/src/static/js/pluginfw/plugins.js:76:43)
    at process._tickCallback (internal/process/next_tick.js:68:7)
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.resolve (path.js:1080:7)
    at loadPlugin (/opt/etherpad-lite/src/static/js/pluginfw/plugins.js:114:28)
    at Promise.all.Object.keys.map (/opt/etherpad-lite/src/static/js/pluginfw/plugins.js:77:35)
    at Array.map (<anonymous>)
    at Object.exports.update (/opt/etherpad-lite/src/static/js/pluginfw/plugins.js:76:43)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by JohnMcLear** [comment]
Tnx will look asap.

**Comment by JohnMcLear** [comment]
FYI ``git clone`` of this repo against ``develop`` works fine.

**Comment by JohnMcLear** [comment]
I'm fixing up some linting then pushing which will push a new version, if that new version doesn't work please let me know :)  Thanks!

**Comment by ypapouin** [comment]
Thanks to you, 0.0.28 works fine.
